export const FilterMenus = [
    { text: 'ALL', variant: 'default'},
    { text: 'PSO' , variant: 'outline'},
    { text: 'Region 9' , variant: 'outline'},
    { text: 'Region 10', variant: 'outline' },
    { text: 'Region 11', variant: 'outline' },
    { text: 'Region 12', variant: 'outline' },
    { text: 'Region 13', variant: 'outline' },
    { text: 'Component 1', variant: 'outline' },
    { text: 'Component 2', variant: 'outline' },
    { text: 'Component 3', variant: 'outline' },
    { text: 'Component 4', variant: 'outline' },
    { text: 'MEL', variant: 'outline' },
    { text: 'SES', variant: 'outline' },
    { text: 'GGU', variant: 'outline' },
    { text: 'ADMIN', variant: 'outline' },
    { text: 'FINANCE', variant: 'outline' },
    { text: 'PROC', variant: 'outline' },
    { text: 'ODPD', variant: 'outline' }
  ];